name: evolocity
channels:
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - expat=2.7.3
  - gawk=5.3.1
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - mafft=7.525
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.12.12
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - anndata==0.12.6
      - array-api-compat==1.12.0
      - biopython==1.86
      - boto3==1.41.5
      - botocore==1.41.5
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - donfig==0.8.1.post1
      - evolocity==1.0.1
      - fair-esm==0.4.0
      - filelock==3.20.0
      - fonttools==4.61.0
      - fsspec==2025.10.0
      - fuzzywuzzy==0.18.0
      - google-crc32c==1.7.1
      - h5py==3.15.1
      - idna==3.11
      - igraph==0.11.9
      - iniconfig==2.3.0
      - jinja2==3.1.6
      - jmespath==1.0.1
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - legacy-api-wrap==1.5
      - llvmlite==0.45.1
      - lmdb==1.7.5
      - loompy==3.0.8
      - louvain==0.8.2
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - natsort==8.4.0
      - networkx==3.6
      - numba==0.62.1
      - numcodecs==0.16.5
      - numpy==2.3.5
      - numpy-groupies==0.11.3
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - packaging==25.0
      - pandas==2.3.3
      - patsy==1.0.2
      - pillow==12.0.0
      - pluggy==1.6.0
      - protobuf==6.33.1
      - pygments==2.19.2
      - pynndescent==0.5.13
      - pyparsing==3.2.5
      - pytest==9.0.1
      - python-dateutil==2.9.0.post0
      - python-igraph==0.11.9
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - s3transfer==0.15.0
      - scanpy==1.11.5
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - scvelo==0.3.3
      - seaborn==0.13.2
      - session-info2==0.2.3
      - six==1.17.0
      - statsmodels==0.14.5
      - sympy==1.14.0
      - tape-proteins==0.5
      - tensorboardx==2.6.4
      - texttable==1.7.0
      - threadpoolctl==3.6.0
      - torch==2.9.1
      - tqdm==4.67.1
      - triton==3.5.1
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - umap-learn==0.5.9.post2
      - urllib3==2.5.0
      - zarr==3.1.5
prefix: /home/brianhie/miniconda/envs/evolocity
