name: epi
channels:
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2021.1.19=h06a4308_0
  - certifi=2020.12.5=py37h06a4308_0
  - cudatoolkit=11.0.221=h6bb024c_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libxml2=2.9.10
  - mafft=7.475=h516909a_0
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1i=h27cfd23_0
  - pip=20.3.1=py37h06a4308_0
  - python=3.7.9=h7579374_0
  - readline=8.0=h7b6447c_0
  - setuptools=51.0.0=py37h06a4308_2
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.11.0
    - anndata==0.7.5
    - astunparse==1.6.3
    - attrs==20.3.0
    - beautifulsoup4==4.9.3
    - biopython==1.76
    - boto3==1.17.7
    - botocore==1.20.7
    - bpemb==0.3.2
    - cachetools==4.2.0
    - cffi==1.14.4
    - chardet==3.0.4
    - cheroot==8.5.1
    - cherrypy==18.6.0
    - click==7.1.2
    - cloudpickle==1.6.0
    - cryptography==3.3.1
    - cvxopt==1.2.5
    - cycler==0.10.0
    - decorator==4.4.2
    - deprecated==1.2.10
    - docx==0.2.4
    #- esm==0.2.0
    - fa2==0.3.5
    - feedparser==6.0.2
    - filelock==3.0.12
    - future==0.18.2
    - fuzzywuzzy==0.18.0
    - gast==0.3.3
    - gensim==3.8.3
    - get-version==2.1
    - google-auth==1.24.0
    - google-auth-oauthlib==0.4.2
    - google-pasta==0.2.0
    - graphtools==1.5.2
    - grpcio==1.34.0
    - h5py==2.10.0
    - hmmlearn==0.2.3
    - hyperopt==0.2.5
    - idna==2.10
    - importlib-metadata==3.3.0
    - iniconfig==1.1.1
    - intervaltree==3.1.0
    - jaraco-classes==3.1.0
    - jaraco-collections==3.0.0
    - jaraco-functools==3.0.1
    - jaraco-text==3.2.0
    - jmespath==0.10.0
    - joblib==1.0.0
    - keras==2.3.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - langdetect==1.0.8
    - legacy-api-wrap==1.2
    - llvmlite==0.35.0
    - lmdb==1.1.1
    - loompy==3.0.6
    - louvain==0.6.1
    - lxml==4.6.2
    - markdown==3.3.3
    - matplotlib==3.3.3
    - more-itertools==8.6.0
    - mpld3==0.3
    - natsort==7.1.0
    - networkx==2.5
    - nltk==3.4.5
    - numba==0.52.0
    - numexpr==2.7.1
    - numpy==1.17.2
    - numpy-groupies==0.9.13
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - packaging==20.8
    - pandas==1.1.5
    - patsy==0.5.1
    - pattern3==3.0.0
    - pdfminer-six==20201018
    - pdfminer3k==1.3.4
    - phate==1.0.4
    - pillow==8.0.1
    - pluggy==0.13.1
    - ply==3.11
    - portend==2.7.0
    - protobuf==3.14.0
    - py==1.10.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pygsp==0.5.1
    - pynndescent==0.5.1
    - pyparsing==2.4.7
    - pytest==6.2.1
    - python-dateutil==2.8.1
    - python-igraph==0.8.3
    - python-levenshtein==0.12.2
    - pytz==2020.4
    - pyyaml==5.3.1
    - regex==2020.11.13
    - requests==2.25.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - s-gd2==1.8
    - s3transfer==0.3.4
    - sacremoses==0.0.43
    - scanpy==1.6.1
    - schema-learn==0.0.6
    - scikit-learn==0.24.0
    - scipy==1.5.4
    - scprep==1.0.11
    - scvelo==0.2.2
    - seaborn==0.11.1
    - segtok==1.5.10
    - sentencepiece==0.1.94
    - setuptools-scm==5.0.1
    - sgmllib3k==1.0.0
    - simplejson==3.17.2
    - sinfo==0.3.1
    - six==1.15.0
    - sklearn==0.0
    - smart-open==4.0.1
    - sortedcontainers==2.3.0
    - soupsieve==2.1
    - sqlitedict==1.7.0
    - statsmodels==0.12.1
    - stdlib-list==0.8.0
    - tables==3.6.1
    - tabulate==0.8.7
    #- tape-proteins==0.4
    - tasklogger==1.0.0
    - tempora==4.0.1
    - tensorboard==2.2.2
    - tensorboard-plugin-wit==1.7.0
    - tensorboardx==2.1
    - tensorflow-estimator==2.2.0
    - tensorflow-gpu==2.2.1
    - termcolor==1.1.0
    - texttable==1.6.3
    - threadpoolctl==2.1.0
    - tokenizers==0.9.4
    - toml==0.10.2
    - torch==1.7.1
    - torchaudio==0.7.2
    - torchvision==0.8.2
    - tqdm==4.54.1
    - transformers==4.0.1
    - typing-extensions==3.7.4.3
    - umap-learn==0.4.6
    - urllib3==1.26.3
    - werkzeug==1.0.1
    - wrapt==1.12.1
    - zc-lockfile==2.0
    - zipp==3.4.0
prefix: /data/cb/brianhie/anaconda3/envs/epi
